services:
  my-apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./login:/var/www/html/
    networks:
      - owais_network
    depends_on:
      - my-mariadb

  my-mariadb:
    container_name: db
    image: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: owais
      MARIADB_DATABASE: owais_db
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d/
      - owais_volume:/var/lib/mysql
    networks:
      - owais_network

volumes:
  owais_volume:

networks:
  owais_network:
